# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='report',
            name='spent_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Spent time'),
        ),
    ]
