# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180421_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='spent_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Spent time'),
        ),
        migrations.AddField(
            model_name='report',
            name='estimate',
            field=models.TimeField(blank=True, null=True, verbose_name='Estimated time'),
        ),
    ]
