# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20180421_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-date_for'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
    ]
