# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20180429_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date_for',
            field=models.DateField(unique_for_date='date_for', verbose_name='Date for'),
        ),
    ]
