# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0010_auto_20180430_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set([('owner', 'date_for')]),
        ),
    ]
